name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ['1.19']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: |
          GOOS=$(echo ${{ matrix.os }} | tr -d -) GOARCH=amd64 go build -o ghstat-${{ matrix.os }}-amd64

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: ghstat-${{ matrix.os }}-amd64
          path: ./ghstat-${{ matrix.os }}-amd64

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          name: ghstat-ubuntu-latest-amd64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ghstat-ubuntu-latest-amd64
            ghstat-windows-latest-amd64
            ghstat-macos-latest-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
